#!/bin/sh
# Edit reapply commit message

commit_msg_file=$1

echo "Reapply \"$(head -n 1 "$commit_msg_file")\"

This reapplies commit $(git show -s --pretty="%H" CHERRY_PICK_HEAD).

$(tail -n +2 "$commit_msg_file")
" > "$commit_msg_file"
