name: Run tests
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner type"
        type: string
      git-version:
        description: "Git version to use"
        type: string

jobs:
  test:
    name: Tests
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats
        id: setup-bats
        shell: bash
        run: |
          mkdir $HOME/bats && cd $HOME/bats
          # Install Bats
          git clone https://github.com/bats-core/bats-core.git
          ./bats-core/install.sh .
          echo "$(readlink -f bin)" >> $GITHUB_PATH
          # Install Bats helpers
          mkdir helpers
          cd helpers
          git clone https://github.com/bats-core/bats-support
          git clone https://github.com/bats-core/bats-assert
          git clone https://github.com/bats-core/bats-file
          cd ..
          echo "bats-helpers-dir=$(readlink -f helpers)" >> $GITHUB_OUTPUT
          # Print Bats version
          echo "$(./bin/bats -v) is installed"
      - name: Setup Git
        uses: isikerhan/setup-git@v1
        with:
          git-version: ${{ inputs.git-version }}
      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "Test Runner"
          git config --global user.email "test.runner@example.com"
          git config --global init.defaultBranch main
      - name: Execute tests
        shell: bash
        if: runner.os != 'macOS'
        run: |
          if bats tests/; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Tests failed! Check the logs for details." >&2
            exit 0
          fi
      - name: Execute tests
        shell: /bin/zsh {0}
        if: runner.os == 'macOS'
        run: |
          if bats tests/; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Tests failed! Check the logs for details." >&2
            exit 0
          fi
        env:
          BATS_HELPERS_DIR: ${{ steps.setup-bats.outputs.bats-helpers-dir }}
